# Spring Boot Configurations
server:
  port: 8080
spring:
  application:
    name: spring-k8s
logging:
  gelf:
    server: graylog-service
    port: 12201
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

# See AppConfig.java for details
app:
  config:
    key-value-pairs:
      key1: value1
      key2: value2
