apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s
          imagePullPolicy: Always
          image: canmogol/spring-k8s:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-service
spec:
  selector:
    app: spring-k8s
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
